#!/bin/zsh

# git
alias gco='git checkout'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit -m'
alias gd='git diff'
alias gf='git fetch'
alias gl='git log --oneline --decorate --all --graph'
alias gm='git merge'
alias gp='git push'
alias grs='git restore'
alias gcl='git clone'