#! /bin/python
import subprocess
import getpass
import os

# Parsing nmcli network list
output = subprocess.check_output("wifi-list", shell=True).decode('utf-8')
output = output.replace('*', ' ')
lines = output.strip().split('\n')[1:]

# Creating dict with indexed options
options = dict()

# Adding options to dict and displaying
for index, line in enumerate(lines):
    split_line = line.split()
    options[index] = split_line[1]
    print(f"{index+1} {split_line[1]}")

# Asking for network and credentials
selection = int(input("Please a network: ")) - 1
network_password = getpass.getpass(prompt="Network Password: ", stream=None)
selected_option = options[selection]

# trying to connect
try:
    cmd = f"nmcli device wifi connect {selected_option} password {network_password}"
    os.system(cmd)
except Exception as e:
    print("Error connecting to network")
